- alias: 'Coach Candle'
  trigger:
    platform: state
    entity_id: input_boolean.test_button_1
    to: 'on'

  action:
  - service: homeassistant.turn_on
    entity_id: light.coach_light
    data:
      brightness: 255
      rgb_color: [255,126,0]
      effect: "Flicker Effect With Custom Values"
#  - service: scene.turn_on
#    data:
#      entity_id: scene.coach_candle_flicker
