esphomeyaml:
  name: tower
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: 'SSID HERE'
  password: 'WIFI_PASSWORD'
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.1.100
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.1.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

# Enable logging
logger:


ota:
  password: 'OTA_PASSWORD'
  
mqtt:
  broker: 192.168.1.12
  username: tower
  password: MQTT_PASSWORD

    
light:
  - platform: fastled_clockless
    chipset: WS2811
    pin: GPIO3
    num_leds: 22
    rgb_order: GRB
    name: "Tower Light"
