- platform: group
  name: Bedroom_Ceiling
  entities:
  - light.bedroom_ceiling_1
  - light.bedroom_ceiling_2
- platform: group
  name: Living_Room_Ceiling
  entities:
  - light.living_room_ceiling_1
  - light.living_room_ceiling_2
  

