- alias: Weekly HA backup
  initial_state: true
  trigger:
    - platform: time
      at: '02:00:00'
  condition:
    - condition: time
      weekday:
        - sat
  action:
    - service: hassio.snapshot_full
      data_template:
        name: Full_Backup_{{ now().strftime('%Y%m%d') }} 
    - service: notify.mail_steve
      data:
        message: "HASS backup has run. the snapshot name is ---->  Full_Backup_{{ now().strftime('%Y%m%d') }} "